spring.application.name=smartNotes Dev
spring.datasource.url=jdbc:h2:file:./data/smartnotes
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.show-sql=true

